### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Rudloff** [2Ra66it/updater-for-spotify#1]
Hello,
Is this code published under an open-source license?
I could not find any license text in the repository.

([Choosing a license](https://choosealicense.com/) helps people know what they can or can't do with your code.)

**Comment by 2Ra66it** [comment]
Hi, yes this code is published under the open-source license, I will add the text of the license later.

**Comment by 2Ra66it** [comment]
Done!

**Comment by Rudloff** [comment]
Thanks!
