### ISSUE TITLE
Unable to download latest version of Spotify

### ISSUE THREAD

**Issue by fakku-inzsasz** [2Ra66it/updater-for-spotify#10]
Updater for Spotify is unable to download new versions. Download Manager instantly says "Download unsuccessful." I cleared app cache, gave all necessary permissions, uninstalled Spotify and still get the same error.

Device Info:
Model: Nokia 6.1 Plus
OS: Android 9 Pie

**Comment by 2Ra66it** [comment]
I apologize for the long answer. 
The issue was fixed in version 1.26.
https://github.com/2Ra66it/updater-for-spotify/releases
