### ISSUE TITLE
Update check interval

### ISSUE THREAD

**Issue by glitchphan** [2Ra66it/updater-for-spotify#12]
PLEASE add an option to change the check interval. Either just a box for X days or whatever. Thanks in advance.

**Comment by 2Ra66it** [comment]
Hi, why is this a necessary feature?

**Comment by glitchphan** [comment]
There are updates to Spotify every day. I don't really want to download the apk every day. Turning off the notification makes it less convenient, though. Then I have to manually open the app.

**Comment by 2Ra66it** [comment]
I added a choice to check for updates, now you can choose: every day, every week, every 3 weeks. Later I will add so that the user can select the interval in days he needs.

**Comment by glitchphan** [comment]
This is awesome. Thank you.
