### ISSUE TITLE
Stuck on downloading

### ISSUE THREAD

**Issue by keganlance** [2Ra66it/updater-for-spotify#13]
Updater for Spotify used to work perfectly. Now when I try to download the latest version, the loading bar just keeps loading and nothing seems to happen. Is there anything I can provide to help?

**Comment by 2Ra66it** [comment]
Hi, could you make sure you are using the latest version of the application (https://github.com/2Ra66it/updater-for-spotify/releases)

**Comment by shawn1thompson** [comment]
Same problem here. I just downloaded the app.

**Comment by keganlance** [comment]
For some reason it works fine again. It seems to not always work. I do use a VPN every now and then. Maybe that has something to do with it?

**Comment by 2Ra66it** [comment]
Fully possible, I need more information about this.

**Comment by shawn1thompson** [comment]
What information do you need?

**Comment by shawn1thompson** [comment]
Today, it started working on its own. Notified me they're an update, downloaded and installed.

**Comment by 2Ra66it** [comment]
The application does not download only when you use VPN?

**Comment by keganlance** [comment]
It doesn't seem to be related to VPN. Tho maybe it does. I was able to download it when on a VPN connected to south korea. Tho I recall without VPN turned on it sometimes didn't work. My GEO is The Netherlands. Tho Spotify is available in the netherlands just normally.

**Comment by TheCodeDestroyer** [comment]
Is it possible you could add some progress percentage or transfered bytes/bytes so we know maybe if its stuck or really slow?

**Comment by toxyxd** [comment]
I found that version 1.34 is working correctly, and version 1.35 doesn't download updates

**Comment by Leptopoda** [comment]
Maybe @keganlance is using android 10. In this release android changed its storage permission api and therefore the app is not working on my device aswell. When being in landscape the download bar is showing an error message (permission denied or something like that).

**Comment by oatberry** [comment]
I am on android 10; v1.3.5 does not work and 1.3.4 does.  I get the same kind of error that @Leptopoda does.

**Comment by 2Ra66it** [comment]
Sorry for the late reply, I released a new version, now everything should work correctly.
https://github.com/2Ra66it/updater-for-spotify/releases

**Comment by TheCodeDestroyer** [comment]
@2Ra66it Heya will you also publish this to FDroid?

**Comment by 2Ra66it** [comment]
@TheCodeDestroyer The update should appear in the near future, unfortunately I do not control the release of updates on f-droid :(
