### ISSUE TITLE
Possible additions / merger with other apps

### ISSUE THREAD

**Issue by keganlance** [2Ra66it/updater-for-spotify#15]
There seem to be several other apps with this kind of functionality like this one:
https://github.com/javiersantos/WhatsAppBetaUpdater/

May be an idea to have one application to update applications which offer an official apk download link?

**Comment by 2Ra66it** [comment]
My application was created only for updating Spotify since It is not available in many countries. And also demonstrate how this can be implemented. If you need an application to update other applications, you can install some kind of market, for example https://aptoide.com/en/home
