### ISSUE TITLE
Updater is serving a modded apk for spotify?

### ISSUE THREAD

**Issue by pitastrudl** [2Ra66it/updater-for-spotify#16]
I am not exactly sure where the apk comes from but if it is aptoide and it's the most popular result, then this application is serving a modded apk which enables premium. Basically this means it's promoting piracy. Is this correct or can we somehow get a untouched pure apk from Spotify?
#11  seems to be outdated. Atleast the link.

![image](https://user-images.githubusercontent.com/2771072/69790346-9dfaac00-11c2-11ea-9ea2-f5877a714e9b.png)

**Comment by 2Ra66it** [comment]
This is not a mod.
