### ISSUE TITLE
Didn't get the update

### ISSUE THREAD

**Issue by rodger-rulez** [2Ra66it/updater-for-spotify#17]
The application does not find updates for spotify, although they are.

**Comment by pdkpv** [comment]
:(

**Comment by 2Ra66it** [comment]
Hi, to get the new version of spotify, I use api aptiode, if you do not see the new version, then it is not on aptiode servers yet.

**Comment by gpchelkin** [comment]
@2Ra66it I can see newer versions like 8.5.47.765 on Aptoide now: https://spotify-muzik-dan-podcast.en.aptoide.com/versions 
But I have version 8.5.46.859 installed on my phone, and Updater is telling me that the latest version is installed now, no updates.

**Comment by rodger-rulez** [comment]
> But I have version 8.5.46.859 installed on my phone, and Updater is telling me that the latest version is installed now, no updates.

Yep
The same thing.., 
Look ss https://imgur.com/a/seQC36c

**Comment by 2Ra66it** [comment]
Hi, I apologize for the long answer, I don’t know what happened, but for some reason aptiode previously distributed a version that is higher than the current one, this is their mistake, at the moment the latest version is spotify 8.5.44.941
