### ISSUE TITLE
Old update

### ISSUE THREAD

**Issue by the-nos4a2** [2Ra66it/updater-for-spotify#26]
Very good app, very helpful, but the version available is an old one. Did the app available version stopped updating with more recent spotify updates?
Also the mod is from techbigs that has a toast message every time you enter the app and it's a bit annoying.

**Comment by 2Ra66it** [comment]
Hey! This is a very strange situation, until the last moment there was the original Spotify, but apparently the Aptiode from which I receive updates began to distribute the modified version. If the situation does not change, I will have to migrate to the new API
