### ISSUE TITLE
Modified versions

### ISSUE THREAD

**Issue by dimqua** [2Ra66it/updater-for-spotify#6]
Can you please allow to download and update some modified versions (libre.io, mobilism, etc.) of the Spotify app?

**Comment by 2Ra66it** [comment]
Hi, I'm sorry for the delay in replying. Unfortunately, this is impossible, because spotfy blocks users who use the modified version of the application spotify :(

**Comment by Novaaaaaaaa** [comment]
@2Ra66it This is simply not true. I'm currently using a modified version of spotify that gives the same features as DogfoodCORE. Once the dust began to settle, they stopped caring again, and there are now many modified versions that work using even some of the latest verions of the original app.

**Comment by Novaaaaaaaa** [comment]
@2Ra66it The current one I use is from https://lynxmods.com, with the latest version being https://drive.google.com/file/d/1iSo36F5j75-r0NYMeqYM-NEJwb0BPtaG/view

I have looked through the code, and found no changes in the code besides obvious things necessary for the mod to work, and a package name change to "Lynxfy". Although the latest version is a little outdated, it is more reputable than the more recent versions found on websites such as http://ihackedit.com, where you tend to download many "phantom" APKs that have no launcher icon, no usable features, but instead many trackers as well as maximum permissions, and malicious code, before the actual package, with all packages being named spotify. You will never know until you open it in package installer and see no icon. I've never had this problem with "Lynxfy" versions whatsoever, and consider them safe.
