### ISSUE TITLE
Please increase versionCode

### ISSUE THREAD

**Issue by IzzySoft** [2Ra66it/updater-for-spotify#7]
With the last release you forgot to increase the `versionCode` [in your gradle](https://github.com/2Ra66it/updater-for-spotify/blob/master/app/build.gradle):

```
        versionCode 1
        versionName "1.08"
```

That way Android would never recognize it as an update – well, and F-Droid wouldn't build the new version. Can you please adjust that? Thanks in advance!

**Comment by IzzySoft** [comment]
Thanks! F-Droid should pick it up shortly then.

**Comment by 2Ra66it** [comment]
Hi, what should I do if f-droid does not pick up the new version?

**Comment by IzzySoft** [comment]
Be patient? :innocent: F-Droid isn't that fast. Give it a week at least, sometimes some things get "hanging" (issues with the build server etc pop up every now and then, plus the queue is not really short currently – see for yourself in [Apps to Update](https://f-droid.org/wiki/page/Category:Apps_to_Update)).

**Comment by 2Ra66it** [comment]
Hi, my application still has not been updated to f-droid

**Comment by IzzySoft** [comment]
Nothing I can do about this. You could create an issue at fdroiddata. I've no idea why it isn't picked up: Auto Update settings seem fine, and your tag as well.
