### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by savenko-egor** [2Ra66it/updater-for-spotify#9]
Please add Spotify changelog to your application.

**Comment by 2Ra66it** [comment]
Hi, I'm not sure that this application needs a changelog

**Comment by savenko-egor** [comment]
I talk about Spotify changelog.
Add to your app changelog from Spotify.
You think this features don't need?

**Comment by 2Ra66it** [comment]
Spotify does not provide changelog for updates, so this is not possible.

**Comment by savenko-egor** [comment]
Oh... Yes. Bad news.
Okay. Thanks for your replies.
